#server:
#  port: 8888
#spring:
#  application:
#    name: toomall-gateway
#  profiles:
#    active: dev
#
#  cloud:
#    nacos:
#      server-addr: 49.232.202.163:8848
#      discovery:
#        server-addr: 49.232.202.163:8848
#      username: nacos
#      password: nacos
#      config:
#        file-extension: yml
